# Generated by Django 5.1.6 on 2025-03-28 17:18

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(verbose_name="texto da pergunta")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Múltipla Escolha"),
                            ("true_false", "Verdadeiro/Falso"),
                            ("matching", "Associação"),
                            ("ordering", "Ordenação"),
                            ("fill_in", "Preencher Lacunas"),
                            ("video_response", "Resposta em Vídeo"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="tipo de questão",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quiz_images/",
                        verbose_name="imagem",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="URL do vídeo")),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Valor em pontos desta questão",
                        verbose_name="pontos",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="ordem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluído"),
                            ("timed_out", "Tempo Esgotado"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="pontuação"
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="percentual de acertos",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="iniciado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluído em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa de Quiz",
                "verbose_name_plural": "Tentativas de Quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="texto da resposta"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="é correta"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Usado para ordenação ou associação",
                        verbose_name="ordem",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explicação mostrada quando esta resposta é selecionada",
                        verbose_name="explicação",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.question",
                        verbose_name="questão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_response",
                    models.TextField(blank=True, verbose_name="resposta em texto"),
                ),
                (
                    "video_response_url",
                    models.URLField(
                        blank=True, verbose_name="URL da resposta em vídeo"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="está correta"),
                ),
                (
                    "points_earned",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="pontos obtidos"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quizzes.question",
                        verbose_name="questão",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selected_in",
                        to="quizzes.answer",
                        verbose_name="respostas selecionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta à Questão",
                "verbose_name_plural": "Respostas às Questões",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tempo máximo em minutos para completar o quiz",
                        verbose_name="limite de tempo (minutos)",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Pontuação mínima percentual para passar no quiz",
                        verbose_name="nota para aprovação (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
    ]
