# Generated by Django 5.1.6 on 2025-03-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
    ]
