# Generated by Django 5.1.6 on 2025-03-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("course_completion", "Conclusão de Curso"),
                            ("lesson_streak", "Sequência de Aulas"),
                            ("quiz_score", "Pontuação em Quiz"),
                            ("participation", "Participação"),
                            ("special", "Especial"),
                        ],
                        max_length=20,
                        verbose_name="tipo de conquista",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievement_icons/",
                        verbose_name="ícone",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="pontos"),
                ),
                (
                    "requirement_description",
                    models.CharField(
                        help_text="Ex: Completar 5 aulas consecutivas",
                        max_length=255,
                        verbose_name="descrição do requisito",
                    ),
                ),
                (
                    "requirement_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Ex: 5 (para completar 5 aulas)",
                        verbose_name="valor do requisito",
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="é secreta"),
                ),
            ],
            options={
                "verbose_name": "Conquista",
                "verbose_name_plural": "Conquistas",
                "ordering": ["achievement_type", "points"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Não Iniciada"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluída"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "video_progress",
                    models.PositiveIntegerField(
                        default=0, verbose_name="progresso do vídeo (segundos)"
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="percentual de progresso"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="último acesso"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluída em"
                    ),
                ),
                (
                    "total_watched_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tempo total assistido (segundos)"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="contagem de visualizações"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "Progresso de Aula",
                "verbose_name_plural": "Progressos de Aulas",
                "ordering": ["lesson__module__order", "lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="StudentAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="conquistado em"
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="visualizado"),
                ),
            ],
            options={
                "verbose_name": "Conquista do Aluno",
                "verbose_name_plural": "Conquistas dos Alunos",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Não Iniciado"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluído"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="percentual de progresso"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="último acesso"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluído em"
                    ),
                ),
                (
                    "completed_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="aulas concluídas"
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de aulas"
                    ),
                ),
                (
                    "quiz_average_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="pontuação média em quizzes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="courses.course",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Curso",
                "verbose_name_plural": "Progressos de Cursos",
                "ordering": ["-last_accessed"],
            },
        ),
    ]
