# Generated by Django 5.1.6 on 2025-03-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="aluno",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="courses.lesson",
                verbose_name="aula",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="aluno",
            ),
        ),
        migrations.AddField(
            model_name="studentachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_achievements",
                to="progress.achievement",
                verbose_name="conquista",
            ),
        ),
        migrations.AddField(
            model_name="studentachievement",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achievement_records",
                to="courses.course",
                verbose_name="curso relacionado",
            ),
        ),
        migrations.AddField(
            model_name="studentachievement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="aluno",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseprogress",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("student", "lesson")},
        ),
        migrations.AlterUniqueTogether(
            name="studentachievement",
            unique_together={("student", "achievement")},
        ),
    ]
