# Generated by Django 5.1.6 on 2025-03-28 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="título")
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "Básico"),
                            ("intermediate", "Intermediário"),
                            ("advanced", "Avançado"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="nível",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_covers/",
                        verbose_name="imagem de capa",
                    ),
                ),
                (
                    "preview_video",
                    models.URLField(
                        blank=True,
                        verbose_name="vídeo de prévia"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ativo")
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="atualizado em"
                    ),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de alunos"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="avaliação média",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")
                        ],
                        verbose_name="avaliação",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="comentário")
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="atualizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de curso",
                "verbose_name_plural": "Avaliações de cursos",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="matriculado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ativo")
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        verbose_name="completo"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último acesso"
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="porcentagem de progresso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="título")
                ),
                ("description", models.TextField(verbose_name="descrição")),
                ("video_url", models.URLField(verbose_name="URL do vídeo")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Duração da aula em minutos",
                        verbose_name="duração em minutos",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="ordem")),
                (
                    "is_free",
                    models.BooleanField(
                        default=False,
                        help_text="Se esta aula está disponível gratuitamente",
                        verbose_name="é gratuita",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ativa")
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="criada em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="atualizada em"
                    ),
                ),
                (
                    "supplementary_material",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Material adicional para a aula "
                            "(links, texto, etc)"
                        ),
                        verbose_name="material complementar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="título")
                ),
                ("description", models.TextField(verbose_name="descrição")),
                ("order", models.PositiveIntegerField(verbose_name="ordem")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ativo")
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="atualizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["course", "order"],
            },
        ),
    ]
