# Generated by Django 5.1.6 on 2025-03-28 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="título")),
                ("message", models.TextField(verbose_name="mensagem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lido")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Agendamento"),
                            ("reschedule", "Reagendamento"),
                            ("cancellation", "Cancelamento"),
                            ("reminder", "Lembrete"),
                        ],
                        default="schedule",
                        max_length=20,
                        verbose_name="tipo de notificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação de Aula",
                "verbose_name_plural": "Notificações de Aula",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(verbose_name="data"),
                ),
                (
                    "start_time",
                    models.TimeField(verbose_name="hora de início"),
                ),
                (
                    "end_time",
                    models.TimeField(verbose_name="hora de término"),
                ),
                ("status", models.CharField(
                    choices=[
                        ("scheduled", "Agendada"),
                        ("cancelled", "Cancelada"),
                        ("completed", "Concluída"),
                        ("missed", "Perdida"),
                    ],
                    default="scheduled",
                    max_length=20,
                    verbose_name="status",
                )),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("group", "Grupo"),
                            ("individual", "Individual"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="tipo de aula",
                    ),
                ),
                (
                    "zoom_link",
                    models.URLField(blank=True, null=True, verbose_name="link do Zoom"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="avaliação"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="feedback"),
                ),
            ],
            options={
                "verbose_name": "Aula Agendada",
                "verbose_name_plural": "Aulas Agendadas",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="dia da semana",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(verbose_name="hora de início"),
                ),
                (
                    "end_time",
                    models.TimeField(verbose_name="hora de término"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="disponível"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Disponibilidade do Professor",
                "verbose_name_plural": "Disponibilidades dos Professores",
                "ordering": ["weekday", "start_time"],
            },
        ),
    ]
