# Generated by Django 5.1.6 on 2025-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Aula Agendada"),
                            ("reminder", "Lembrete de Aula"),
                            ("cancellation", "Cancelamento"),
                            ("rescheduled", "Reagendamento"),
                        ],
                        max_length=20,
                        verbose_name="tipo de notificação",
                    ),
                ),
                ("message", models.TextField(verbose_name="mensagem")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
                ("read", models.BooleanField(default=False, verbose_name="lido")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lido em"),
                ),
            ],
            options={
                "verbose_name": "Notificação de Aula",
                "verbose_name_plural": "Notificações de Aulas",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="data")),
                ("start_time", models.TimeField(verbose_name="horário de início")),
                ("end_time", models.TimeField(verbose_name="horário de término")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("confirmed", "Confirmada"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                            ("missed", "Perdida"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Tema/assunto a ser trabalhado na aula",
                        max_length=200,
                        verbose_name="tema",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações ou requisitos específicos para a aula",
                        verbose_name="observações",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Link para a sala virtual da aula",
                        verbose_name="link da reunião",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback do professor após a aula",
                        verbose_name="feedback",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Aula Agendada",
                "verbose_name_plural": "Aulas Agendadas",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="dia da semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="horário de início")),
                ("end_time", models.TimeField(verbose_name="horário de término")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Disponibilidade de Professor",
                "verbose_name_plural": "Disponibilidades de Professores",
                "ordering": ["teacher", "weekday", "start_time"],
            },
        ),
    ]
