# Generated by Django 5.1.6 on 2025-03-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="destinatário",
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_classes_as_student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="aluno",
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_classes_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="professor",
            ),
        ),
        migrations.AddField(
            model_name="classnotification",
            name="scheduled_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="scheduling.scheduledclass",
                verbose_name="aula agendada",
            ),
        ),
        migrations.AddField(
            model_name="teacheravailability",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="professor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacheravailability",
            unique_together={("teacher", "weekday", "start_time", "end_time")},
        ),
    ]
